name: mgstellargraph

channels:
- conda-forge
- stellargraph

dependencies:
# dev environment
  - python=3.8
  - black
  - conda-forge::pre-commit
  - setuptools
  - metagraph::metagraph-dev

# metagraph-stellargraph dependencies
  - stellargraph::stellargraph