name: mg

channels:
- conda-forge
- metagraph/label/dev
- stellargraph

dependencies:
# dev environment
  - python=3.7
  - coverage
  - pytest
  - pytest-cov
  - black
  - conda-forge::pre-commit
  - setuptools
  - metagraph::metagraph

# metagraph-stellargraph dependencies
  - stellargraph::stellargraph