name: mg

channels:
- conda-forge
- metagraph/label/dev
- stellargraph

dependencies:
# dev environment
  - python=3.8
  - metagraph-dev
  - black

# metagraph-stellargraph dependencies
  - metagraph
  - stellargraph